# Generated by Django 2.1.7 on 2019-03-16 03:39

import apps.courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=apps.courses.fields.OrderField(blank=True, null=True),
        ),
    ]
