# Generated by Django 2.1.7 on 2019-03-16 03:41

import apps.courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190316_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=apps.courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
